apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmqcli.fullname" .}}
  namespace: {{ .Values.namespace.name }}
  labels: 
  {{- include "rabbitmqcli.labels" . | nindent 4 }}
data:
  api_prefix: {{ .Values.config.api_prefix }}