apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rabbitmqcli.fullname" .}}
  namespace: {{ .Values.namespace.name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
    {{- include "rabbitmqcli.selectorLabels" . | nindent 6 }}